package com.socialsearcher.model;
// Generated 05.03.2017 17:33:45 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SocialPersonGroup generated by hbm2java
 */
@Entity
@Table(name = "SocialPersonGroup", catalog = "socialappsearcher")
public class SocialPersonGroup implements java.io.Serializable {

	private Integer id;
	private int userId;
	private int socialPersonId;

	public SocialPersonGroup() {
	}

	public SocialPersonGroup(int userId, int socialPersonId) {
		this.userId = userId;
		this.socialPersonId = socialPersonId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "social_person_id", nullable = false)
	public int getSocialPersonId() {
		return this.socialPersonId;
	}

	public void setSocialPersonId(int socialPersonId) {
		this.socialPersonId = socialPersonId;
	}

}
