package com.socialsearcher.model;
// Generated 05.03.2017 17:33:45 by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "UserRole", catalog = "socialappsearcher")
public class UserRole implements java.io.Serializable {

	private Integer userId;
	private String name;
	private String role;
	private int userIdFk;

	public UserRole() {
	}

	public UserRole(String name, String role, int userIdFk) {
		this.name = name;
		this.role = role;
		this.userIdFk = userIdFk;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "name", nullable = false, length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "role", nullable = false, length = 50)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "user_id_fk", nullable = false)
	public int getUserIdFk() {
		return this.userIdFk;
	}

	public void setUserIdFk(int userIdFk) {
		this.userIdFk = userIdFk;
	}

}
