package com.diskservice.model;
// Generated 27.04.2016 10:16:04 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Disk generated by hbm2java
 */
@Entity
@Table(name = "disk", catalog = "disks")
public class Disk implements java.io.Serializable {

	private Integer diskId;
	private User user;
	private String title;
	private Set<Takenitem> takenitems = new HashSet<Takenitem>(0);

	public Disk() {
	}

	public Disk(User user, String title) {
		this.user = user;
		this.title = title;
	}

	public Disk(User user, String title, Set<Takenitem> takenitems) {
		this.user = user;
		this.title = title;
		this.takenitems = takenitems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "disk_id", unique = true, nullable = false)
	public Integer getDiskId() {
		return this.diskId;
	}

	public void setDiskId(Integer diskId) {
		this.diskId = diskId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "disk")
	public Set<Takenitem> getTakenitems() {
		return this.takenitems;
	}

	public void setTakenitems(Set<Takenitem> takenitems) {
		this.takenitems = takenitems;
	}

}
