package com.diskservice.model;
// Generated 27.04.2016 10:16:04 by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Takenitem generated by hbm2java
 */
@Entity
@Table(name = "takenitem", catalog = "disks")
public class Takenitem implements java.io.Serializable {

	private Integer takenItemId;
	private Disk disk;
	private User user;

	public Takenitem() {
	}

	public Takenitem(Disk disk, User user) {
		this.disk = disk;
		this.user = user;
	}
	

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "taken_item_id", unique = true, nullable = false)
	public Integer getTakenItemId() {
		return this.takenItemId;
	}

	public void setTakenItemId(Integer takenItemId) {
		this.takenItemId = takenItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disk_id", nullable = false)
	public Disk getDisk() {
		return this.disk;
	}

	public void setDisk(Disk disk) {
		this.disk = disk;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

}
