package com.diskservice.model;
// Generated 27.04.2016 10:16:04 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "disks")
public class User implements java.io.Serializable {

	private Integer userId;
	private String login;
	private String password;
	private byte enabled;
	private Set<Disk> disks = new HashSet<Disk>(0);
	private Set<Userrole> userroles = new HashSet<Userrole>(0);
	private Set<Takenitem> takenitems = new HashSet<Takenitem>(0);

	public User() {
	}

	public User(byte enabled) {
		this.enabled = enabled;
	}

	public User(String login, String password, byte enabled, Set<Disk> disks, Set<Userrole> userroles,
			Set<Takenitem> takenitems) {
		this.login = login;
		this.password = password;
		this.enabled = enabled;
		this.disks = disks;
		this.userroles = userroles;
		this.takenitems = takenitems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "login", length = 50)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Disk> getDisks() {
		return this.disks;
	}

	public void setDisks(Set<Disk> disks) {
		this.disks = disks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Userrole> getUserroles() {
		return this.userroles;
	}

	public void setUserroles(Set<Userrole> userroles) {
		this.userroles = userroles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Takenitem> getTakenitems() {
		return this.takenitems;
	}

	public void setTakenitems(Set<Takenitem> takenitems) {
		this.takenitems = takenitems;
	}

}
